export interface ExcelData {
    // Groom
    gFirst: string;
    gMiddle: string;
    gLast: string;
    gSuffix?: string;
    gCustomSuffix?: string;
    gBday: string;
    gAge: number;
    gBirthPlace?: string;
    gBirthCountry?: string;
    gTown: string;
    gProv: string;
    gBrgy: string;
    gCountry: string;
    gCitizen: string;
    gReligion: string;
    gCustomReligion?: string;
    gStatus: string;
    gDissolvedHow?: string;
    gDissolvedPlace?: string;
    gDissolvedCountry?: string;
    gDissolvedDate?: string;
    gRelationshipDegree?: string;
    gFathF: string;
    gFathM: string;
    gFathL: string;
    gFathSuffix?: string;
    gFathCustomSuffix?: string;
    gMothF: string;
    gMothM: string;
    gMothL: string;
    gMothSuffix?: string;
    gMothCustomSuffix?: string;
    gGiverF: string;
    gGiverM: string;
    gGiverL: string;
    gGiverSuffix?: string;
    gGiverCustomSuffix?: string;
    gGiverRelation: string;
    gGiverOtherTitle?: string;

    // Groom ID
    gIdType?: string;
    gIdNo?: string;
    gIdCustomType?: string;
    gIncludeId?: boolean;
    gGiverIdType?: string;
    gGiverIdNo?: string;
    gGiverIdCustomType?: string;
    gGiverIncludeId?: boolean;

    // Bride
    bFirst: string;
    bMiddle: string;
    bLast: string;
    bSuffix?: string;
    bCustomSuffix?: string;
    bBday: string;
    bAge: number;
    bBirthPlace?: string;
    bBirthCountry?: string;
    bTown: string;
    bProv: string;
    bBrgy: string;
    bCountry: string;
    bCitizen: string;
    bReligion: string;
    bCustomReligion?: string;
    bStatus: string;
    bDissolvedHow?: string;
    bDissolvedPlace?: string;
    bDissolvedCountry?: string;
    bDissolvedDate?: string;
    bRelationshipDegree?: string;
    bFathF: string;
    bFathM: string;
    bFathL: string;
    bFathSuffix?: string;
    bFathCustomSuffix?: string;
    bMothF: string;
    bMothM: string;
    bMothL: string;
    bMothSuffix?: string;
    bMothCustomSuffix?: string;
    bGiverF: string;
    bGiverM: string;
    bGiverL: string;
    bGiverSuffix?: string;
    bGiverCustomSuffix?: string;
    bGiverRelation: string;
    bGiverOtherTitle?: string;

    // Bride ID
    bIdType?: string;
    bIdNo?: string;
    bIdCustomType?: string;
    bIncludeId?: boolean;
    bGiverIdType?: string;
    bGiverIdNo?: string;
    bGiverIdCustomType?: string;
    bGiverIncludeId?: boolean;

    // Metadata
    applicationCode: string;
    coupleImagePath?: string;
    imageExtension?: string;
    contactNumber?: string;
    employeeName?: string;
    registryNumber?: string;
}
